### ISSUE TITLE
Chart not load when there are lots of nodes

### ISSUE THREAD

**Issue by moeiscool** [visjs-community/vis#2]
I have googled for a while and can't find a clean solution. Is there some option I can put to just force it to complete? because the chart is actually drawn, its just `hidden` and I can't scroll it when I unhide it.

thanks for your hardwork on this :)

**Comment by micahstubbs** [comment]
hi @moeiscool, I'd recommend to try with a smaller number of nodes.  For when you have more than a few thousand nodes in-browser graph layout and and rendering gets expensive.  You may want to try other libraries that do less, but perform a bit faster.

This repo has a nice list with some benchmarks https://github.com/anvaka/graph-drawing-libraries

You could also try Gephi on the desktop - it can handle large graphs, and can be useful for prototyping before you move to the browser with a library like vis.  https://gephi.org/

**Comment by micahstubbs** [comment]
some new research that may be helpful https://twitter.com/rpgove/status/1134511233389010946?s=19
